# Generated by Django 4.2.11 on 2024-05-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_useprofile_agent_organisation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UseProfile',
            new_name='UserProfile',
        ),
    ]
