# Generated by Django 4.2.11 on 2024-06-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_folder_foldercontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foldercontent',
            name='file',
        ),
    ]
