# Generated by Django 4.2.11 on 2024-06-08 04:33

from django.db import migrations, models
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_remove_foldercontent_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldercontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=leads.models.handle_upload_custom_files),
        ),
    ]
