# Generated by Django 4.2.11 on 2024-06-08 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_foldercontent_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FolderContent',
        ),
    ]
