# Generated by Django 4.2.11 on 2024-05-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_converted_date_lead_profile_picture_followup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_agent',
            new_name='is_lvl1',
        ),
    ]
