# Generated by Django 4.2.11 on 2024-06-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_folderdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('进行中', '进行中'), ('已完成', '已完成'), ('待跟进', '待跟进'), ('待递交', '待递交'), ('取消', '取消')], max_length=20, null=True),
        ),
    ]
