# Generated by Django 4.2.11 on 2024-05-24 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_rename_is_organiser_user_is_lvl2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='casefield',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_casefield_per_user'),
        ),
    ]
