# Generated by Django 4.2.11 on 2024-05-25 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_alter_casefield_field_type_casevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefield',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
        migrations.AlterField(
            model_name='casevalue',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extrafields', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='casevalue',
            name='value_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
