# Generated by Django 4.2.11 on 2024-05-26 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_alter_casefield_user_alter_casevalue_lead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
