# Generated by Django 4.2.11 on 2024-09-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_alter_team_team_leader'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('team', 'member'), name='unique_team_member'),
        ),
    ]
