# Generated by Django 4.2.11 on 2024-05-26 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_remove_lead_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='converted_date',
        ),
    ]
