# Generated by Django 4.2.11 on 2024-09-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_lead_shared_commission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='shared_commission',
            new_name='co_commission',
        ),
    ]
