# Generated by Django 4.2.11 on 2024-05-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_user_is_lvl3'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lvl4',
            field=models.BooleanField(default=False),
        ),
    ]
