# Generated by Django 4.2.11 on 2024-09-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_workreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkReport',
        ),
    ]
