# Generated by Django 4.2.11 on 2024-05-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='commission',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='quote',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
