# Generated by Django 4.2.11 on 2024-05-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_lead_commission_lead_completed_lead_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='commission',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lead',
            name='quote',
            field=models.IntegerField(default=0),
        ),
    ]
