# Generated by Django 4.2.11 on 2024-11-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_workreport_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
