# Generated by Django 4.2.11 on 2024-05-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_alter_agent_user_alter_manager_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='profile_picture',
        ),
    ]
