# Generated by Django 4.2.11 on 2024-05-27 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_remove_lead_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='age',
        ),
        migrations.AddField(
            model_name='lead',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.manager'),
        ),
    ]
